"""
Pulls real regulatory/legal text from Hugging Face's `pile-of-law/pile-of-law`
dataset and writes it to `data/raw/dapt/*.txt`, where `chunk_text.py` picks
it up. This replaces manually sourcing DAPT text — you don't hand-collect
10-20M tokens, you stream them from an existing public legal corpus.

Streamed (`streaming=True`), so it never loads a full subset into memory —
required to stay inside Colab's ~12GB system RAM, same constraint
`chunk_text.py` is built around.

Default subsets are the ones most relevant to a *compliance* auditor
(rather than e.g. case law or contracts), out of pile-of-law's ~35
available configs:
    - cfr              Code of Federal Regulations
    - eurlex           EU legislation (GDPR-adjacent)
    - privacy_policies Real privacy policy text
    - tos              Real Terms of Service text (complements the
                        LexGLUE unfair_tos SFT source — DAPT sees the
                        vocabulary, SFT sees labeled violations of it)

pile-of-law is a script-based dataset (a `pile-of-law.py` loading
script on the Hub, not plain Parquet/Arrow files), and `datasets>=3.0`
removed support for loading scripts entirely — `trust_remote_code`
no longer overrides that, it just silently does nothing. The fix is
to load from the Hub's auto-generated Parquet mirror instead of the
default branch: every dataset gets one at `refs/convert/parquet`,
built directly from the underlying data files without running the
loading script at all, so it works the same on any `datasets` version.

Usage:
    python data/scripts/download_corpus.py \
        --subsets cfr eurlex privacy_policies tos \
        --max_docs_per_subset 1500 \
        --output_dir data/raw/dapt
"""
import argparse
import os
from typing import List

from datasets import load_dataset

AVAILABLE_SUBSETS = {
    "cfr",
    "eurlex",
    "privacy_policies",
    "tos",
    "uscode",
    "state_codes",
    "constitutions",
    "echr",
}

DEFAULT_SUBSETS = ["cfr", "eurlex", "privacy_policies", "tos"]

# Rough chars-per-token estimate for a stopping-criterion proxy only — the
# real, exact token count is computed later by chunk_text.py's tokenizer.
# This just avoids downloading far more raw text than the DAPT target
# (10-20M tokens) needs.
APPROX_CHARS_PER_TOKEN = 4


def download_subset(
    subset: str,
    output_dir: str,
    max_docs: int,
    max_chars: int,
    use_parquet_mirror: bool = True,
) -> int:
    if subset not in AVAILABLE_SUBSETS:
        raise ValueError(
            f"Unknown subset '{subset}'. Known compliance-relevant subsets: "
            f"{sorted(AVAILABLE_SUBSETS)}. See the pile-of-law dataset card "
            f"on Hugging Face for the full list if you want a different one."
        )

    load_kwargs = dict(
        path="pile-of-law/pile-of-law",
        name=subset,
        split="train",
        streaming=True,
    )
    if use_parquet_mirror:
        # Bypasses the dataset's loading script — required on datasets>=3.0,
        # which no longer executes loading scripts at all (trust_remote_code
        # included). Falls back to the default (script-based) load below if
        # the caller explicitly disables this, e.g. on an older pinned
        # `datasets` version that still supports scripts.
        load_kwargs["revision"] = "refs/convert/parquet"

    try:
        dataset = load_dataset(**load_kwargs)
    except Exception as e:
        if use_parquet_mirror:
            raise RuntimeError(
                f"Failed to load subset '{subset}' from the refs/convert/parquet "
                f"mirror. This branch is auto-generated by the Hub for every "
                f"dataset, but generation can lag for very large ones — check "
                f"https://huggingface.co/datasets/pile-of-law/pile-of-law/tree/refs%2Fconvert%2Fparquet "
                f"to confirm the subset is listed there. Original error: {e}"
            ) from e
        raise

    out_path = os.path.join(output_dir, f"{subset}.txt")
    n_docs = 0
    n_chars = 0

    with open(out_path, "w", encoding="utf-8") as out_f:
        for example in dataset:
            text = example.get("text", "")
            if not text or not text.strip():
                continue

            out_f.write(text.strip() + "\n\n")
            n_docs += 1
            n_chars += len(text)

            if n_docs >= max_docs or n_chars >= max_chars:
                break

    return n_docs


def download_corpus(
    subsets: List[str],
    output_dir: str,
    max_docs_per_subset: int,
    max_tokens_per_subset: int,
    use_parquet_mirror: bool = True,
) -> None:
    os.makedirs(output_dir, exist_ok=True)
    max_chars_per_subset = max_tokens_per_subset * APPROX_CHARS_PER_TOKEN

    for subset in subsets:
        print(f"Downloading '{subset}' (up to {max_docs_per_subset} docs / "
              f"~{max_tokens_per_subset:,} tokens)...")
        n_docs = download_subset(
            subset=subset,
            output_dir=output_dir,
            max_docs=max_docs_per_subset,
            max_chars=max_chars_per_subset,
            use_parquet_mirror=use_parquet_mirror,
        )
        print(f"  wrote {n_docs} documents to {output_dir}/{subset}.txt")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--subsets", nargs="+", default=DEFAULT_SUBSETS,
        help=f"pile-of-law configs to pull. Known: {sorted(AVAILABLE_SUBSETS)}",
    )
    parser.add_argument("--output_dir", default="data/raw/dapt")
    parser.add_argument("--max_docs_per_subset", type=int, default=1500)
    parser.add_argument(
        "--max_tokens_per_subset", type=int, default=5_000_000,
        help="Approximate stopping point per subset — real token count is "
             "measured later by chunk_text.py, this is just to avoid "
             "over-downloading raw text.",
    )
    parser.add_argument(
        "--no_parquet_mirror", action="store_true",
        help="Load from the dataset's default (script-based) branch instead of "
             "refs/convert/parquet. Only useful on an older pinned `datasets` "
             "version that still executes loading scripts — on datasets>=3.0 "
             "this will fail the same way the original bug report did.",
    )
    args = parser.parse_args()

    download_corpus(
        subsets=args.subsets,
        output_dir=args.output_dir,
        max_docs_per_subset=args.max_docs_per_subset,
        max_tokens_per_subset=args.max_tokens_per_subset,
        use_parquet_mirror=not args.no_parquet_mirror,
    )


if __name__ == "__main__":
    main()